spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_NAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  servlet:
    context-path: /api
  port: ${SERVER_PORT}

bsm:
  client_id: ${BSM_CLIENT_ID}
  client_secret: ${BSM_CLIENT_SECRET}
  redirect_uri: ${BSM_REDIRECT_URI}

jwt:
  secretKey: ${JWT_SECRET_KEY}
  accessExp: ${JWT_ACCESS_TOKEN_EXP}
  refreshExp: ${JWT_REFRESH_TOKEN_EXP}
